version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - TZ=America/Los_Angeles
    restart: always

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
      - DB_HOST=localhost  # This will be replaced by the script
      - DB_USER=root
      - DB_PASSWORD=seva@1633
      - DB_NAME=seva_new
      - TZ=America/Los_Angeles
    depends_on:
      - mysql
    restart: always

  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: seva@1633
      MYSQL_DATABASE: seva_new
      TZ: America/Los_Angeles
    ports:
      - "3307:3306"
    restart: always
