# Use the official Node.js image as the base image
FROM node:14

# Create and change to the app directory
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

# Expose the port the server will run on
EXPOSE 5000

# Start the server
CMD ["node", "server.js"]
